// AUTO-GENERATED by scripts/build-soul-templates.mjs — do not edit.
// Bumped on every rebuild so the client can cache-bust the JSON catalog.
export const SOUL_TEMPLATES_BUILD_ID = "20260424204057829";
